name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: build release 
      run: ./gradlew assembleRelease
    - name: "Run test suite"
      uses: msfjarvis/setup-android@1.0
      with:
        entrypoint: ./gradlew
        args: dependencies spotlessApply detekt assembleDebug
